{{- if and .Values.serviceAccount .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "samurai-app.fullname" .) }}
  namespace: {{ .Values.serviceAccount.namespace | default .Release.Namespace }}
{{- end }}
